basic.showIcon(IconNames.Happy)
basic.forever(function () {
    CutebotPro.colorLight(CutebotProRGBLight.RGBA, 0xffff00)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.motors(100, 40)
    basic.pause(1000)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.forward()
    basic.pause(200)
    cuteBot.motors(100, 40)
    basic.pause(1000)
    cuteBot.forward()
    basic.pause(200)
})
